name: Generate Snake on Profile
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "* */36 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: Platane/snk@v2
      with:
        github_user_name: ${{ github.repository_owner }}
        outputs: |
          dist/github-snake.svg?pallete=github&color_snake=#73a9ad&color_dots=#e6fffd,#aee2ff,#acbcff,#b799ff,#070a5
          - name: push github-contribution-grid-snake.svg to the output branch
    - uses: crazy-max/ghaction-github-pages@v3.1.0
      with:
          target_branch: output
          build_dir: dist
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
